---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_terminal: true
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: false
dockitems_remove: []
# - Launchpad
# - TV
# - Podcasts
# - 'App Store'
dockitems_persist:
  - name: "Arc"
    path: "/Applications/Arc.app"
  - name: "Notion"
    path: "/Applications/Notion.app"
  - name: "Visual Studio Code"
    path: "/Applications/Visual Studio Code.app"
  - name: "Microsoft Teams"
    path: "/Applications/Microsoft Teams.app"
  - name: "Discord"
    path: "/Applications/Discord.app"
  - name: "GitKraken"
    path: "/Applications/GitKraken.app"

configure_sudoers: false
sudoers_custom_config: |
  # Allow users in admin group to use sudo with no password.
  %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/JonathanXDR/Dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_files:
  - .bash_profile
  - .bashrc
  - .gitconfig
  - .npmrc
  - .zprofile
  - .zshrc
  - Brewfile

homebrew_installed_packages:
  - python
  - azure-cli
  - bash
  - emacs
  - cloudflared
  - colima
  - cowsay
  - curl
  - dockutil
  - node
  - eslint
  - ffmpeg
  - gh
  - git
  - grep
  - helm
  - jq
  - k9s
  - lolcat
  - mackup
  - mariadb
  - minikube
  - nvm
  - opa
  - openjdk
  - poetry
  - postgresql
  - prettier
  - putty
  - redis
  - snyk-cli
  - speedtest-cli
  - swagger-codegen
  - telnet
  - vite
  - wget
  - yt-dlp
  - zsh

homebrew_taps:
  - homebrew/autoupdate
  - homebrew/bundle
  - homebrew/cask
  - homebrew/core
  - homebrew/services
  - ubuntu/microk8s

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  # browsers
  - arc
  - google-chrome
  # dev
  - docker
  - gitkraken
  - github
  - fig
  - visual-studio-code
  - jetbrains-toolbox
  - intellij-idea
  - android-studio
  - tableplus
  - mongodb-compass
  - httpie
  - postman
  - asset-catalog-tinkerer
  - sf-symbols
  - unity-hub
  # productivity
  - figma
  - notion
  - miro
  - obs
  - blender
  - citrix-workspace
  - bricklink-studio
  - autodesk-fusion360
  # communication
  - discord
  - microsoft-teams
  # macos tools
  - tg-pro
  - raycast
  - bartender
  - vivid
  - soundsource
  - aldente
  - nordvpn
  - logi-options-plus
  - focusrite-control-2
  # gaming
  - steam
  - minecraft
  - dolphin
  - openemu
  - desmume
  # other
  - keyboardcleantool
  - intune-company-portal
  - adobe-acrobat-reader

# See `JonathanXDR.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 310633997, name: "WhatsApp (23.23.81)" }
  - { id: 1502839586, name: "Hand Mirror (3.0.1)" }
  - {
      id: 1576663233,
      name: "Alto's Adventure The Spirit of the Mountain (1.0.7)",
    }
  - { id: 462058435, name: "Microsoft Excel (16.79.1)" }
  - { id: 1606941598, name: "Affinity Publisher 2 (2.3.0)" }
  - { id: 1462114288, name: "Grammarly for Safari (9.70)" }
  - { id: 1529448980, name: "Reeder (5.4)" }
  - { id: 682658836, name: "GarageBand (10.4.9)" }
  - { id: 1496833156, name: "Playgrounds (4.4)" }
  - { id: 1527569581, name: "Neon Beats (1.19)" }
  - { id: 1044549675, name: "Elmedia Video Player (8.17)" }
  - { id: 1037126344, name: "Apple Configurator (2.17)" }
  - { id: 462054704, name: "Microsoft Word (16.79.1)" }
  - { id: 424389933, name: "Final Cut Pro (10.7)" }
  - { id: 1616831348, name: "Affinity Designer 2 (2.3.0)" }
  - { id: 634148309, name: "Logic Pro (10.8.1)" }
  - { id: 497799835, name: "Xcode (15.0.1)" }
  - { id: 1491129197, name: "Asphalt 9 (43403)" }
  - { id: 425424353, name: "The Unarchiver (4.3.6)" }
  - { id: 1274495053, name: "Microsoft To Do (2.110)" }
  - { id: 1616822987, name: "Affinity Photo 2 (2.3.0)" }
  - { id: 441258766, name: "Magnet (2.13.0)" }
  - { id: 434290957, name: "Motion (5.7)" }
  - { id: 1538650027, name: "The Lost City (1.1.6)" }
  - { id: 462062816, name: "Microsoft PowerPoint (16.79.1)" }
  - { id: 1444383602, name: "Goodnotes (6.2.13)" }
  - { id: 1538878817, name: "UTM (4.4.4)" }
  - { id: 899247664, name: "TestFlight (3.3.0)" }
  - { id: 823766827, name: "OneDrive (23.221.1024)" }
  - { id: 409201541, name: "Pages (13.2)" }
  - { id: 424390742, name: "Compressor (4.7)" }
  - { id: 803453959, name: "Slack (4.35.130)" }
  - { id: 640199958, name: "Developer (10.4.1)" }
  - { id: 784801555, name: "Microsoft OneNote (16.79)" }
  - { id: 985367838, name: "Microsoft Outlook (16.79.2)" }
  - { id: 408981434, name: "iMovie (10.4)" }
  - { id: 409203825, name: "Numbers (13.2)" }
  - { id: 634159523, name: "MainStage (3.6.5)" }
  - { id: 1549961729, name: "com.jbapps.MangoMacos (4.3.0)" }
  - { id: 1539172625, name: "AngryBirdsReloaded (2.6.17163)" }
  - { id: 409183694, name: "Keynote (13.2)" }
  - { id: 967805235, name: "Paste (4.1.3)" }
  - { id: 1018301773, name: "AdBlock Pro (10.6.1)" }

mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
